apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.14.1
        ports:
        - containerPort: 5000
        args:
          - "--backend-store-uri"
          - "postgresql://mlflow:mlflow@postgres-service:5432/mlflow"
          - "--default-artifact-root"
          - "gs://churn-prediction-ai-agent/mlflow"
          - "--host"
          - "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000
